// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Coordinate struct {
	ID  uuid.UUID
	Lon sql.NullFloat64
	Lat sql.NullFloat64
}

type WeatherCondition struct {
	ID          uuid.UUID
	ConditionID sql.NullInt32
	Main        sql.NullString
	Description sql.NullString
	Icon        sql.NullString
}

type WeatherDatum struct {
	ID                  uuid.UUID
	WeatherConditionsID sql.NullInt32
	CoordinatesID       uuid.NullUUID
	CityName            sql.NullString
	Country             sql.NullString
	Temperature         sql.NullFloat64
	FeelsLike           sql.NullFloat64
	TempMin             sql.NullFloat64
	TempMax             sql.NullFloat64
	Pressure            sql.NullInt32
	Humidity            sql.NullInt32
	SeaLevel            sql.NullInt32
	GrndLevel           sql.NullInt32
	Visibility          sql.NullInt32
	WindSpeed           sql.NullFloat64
	WindDeg             sql.NullInt32
	Cloudiness          sql.NullInt32
	Timestamp           sql.NullTime
	Sunrise             sql.NullTime
	Sunset              sql.NullTime
	Timezone            sql.NullInt32
}
