// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: weather_data_conditions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertWeatherDataConditions = `-- name: InsertWeatherDataConditions :one
INSERT INTO weather_data_conditions(
    weather_data_id,
    condition_id
)
VALUES(
    $1,
    $2
)
RETURNING weather_data_id, condition_id
`

type InsertWeatherDataConditionsParams struct {
	WeatherDataID uuid.UUID
	ConditionID   int32
}

func (q *Queries) InsertWeatherDataConditions(ctx context.Context, arg InsertWeatherDataConditionsParams) (WeatherDataCondition, error) {
	row := q.db.QueryRowContext(ctx, insertWeatherDataConditions, arg.WeatherDataID, arg.ConditionID)
	var i WeatherDataCondition
	err := row.Scan(&i.WeatherDataID, &i.ConditionID)
	return i, err
}
